create sequence hibernate_sequence start 1 increment 1;
create table image
(
    id int8 not null,
    bytes oid not null,
    content_type varchar(255),
    name varchar(255),
    original_file_name varchar(255),
    size int8 not null, primary key (id)
);
create table img_prod
(
    img_id int8,
    prod_id int8 not null,
    primary key (prod_id)
);

create table products
(
    id int8 generated by default as identity,
    created_at timestamp, description text,
    price numeric(19, 2) not null,
    title varchar(255),
    weight_and_piece varchar(255),
    product_type_id int8 not null,
    primary key (id)
);

create table types_of_products
(
    id int8 generated by default as identity,
    created_at timestamp default CURRENT_TIMESTAMP,
    type_name varchar(255),
    primary key (id)
);

alter table if exists img_prod
    add constraint img_prod_fk_image
    foreign key (img_id) references image;

alter table if exists img_prod
    add constraint img_peod_fk_products
    foreign key (prod_id) references products;

alter table if exists products
add constraint products_fk_types_of_products
foreign key (product_type_id) references types_of_products;